test('Hello', () => {

})

test('Failed', () => {
    throw new Error('Failed!')
})